library(sloop)
otype(1:10)
otype(mtcars)
mle_obj <- stats4::mle(function(x = 1) (x - 2) ^ 2)
otype(mle_obj)

# A base object:
is.object(1:10)
sloop::otype(1:10)
# An OO object
is.object(mtcars)
sloop::otype(mtcars)
attr(1:10, "class")
attr(mtcars, "class")

x <- matrix(1:4, nrow = 2)
class(x)
sloop::s3_class(x)

typeof(1:10)
typeof(mtcars)
typeof(NULL)
typeof(1L)
typeof(1i)
typeof(mean)
typeof(`[`)
typeof(sum)    
typeof(globalenv())
mle_obj <- stats4::mle(function(x = 1) (x - 2) ^ 2)
typeof(mle_obj)
typeof(quote(a))
typeof(quote(a + 1))
typeof(formals(mean))
